# Generated by Django 4.1.1 on 2022-09-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eApp', '0005_assignment_instruction_alter_assignment_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='PRN',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='identity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='identity',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacher',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
    ]
